### ISSUE TITLE
Import my own robot?

### ISSUE THREAD

**Issue by Stalkerfish** [InfoSphereAC/RoboSim#9]
Does it have any way to import my own Lego Build?

**Comment by thiemol** [comment]
No sorry. The 3D Modell is hard coded. You have to change the model on code.

**Comment by Stalkerfish** [comment]
Do you have any instructions on how to do it?

**Comment by thiemol** [comment]
In the dir graphics you find all the objects and textures. The objects and textures are loaded over SDL. You have ti look at this sections in code and change the objects and textures. Sorry that I can*t help more, but the last time I worked on that is 5 years ago and nobody joints the repo since then.
